a = int(input("enter a number: "))
b = int(input("enter a number: "))
print("sum of two nubers: ", a+b)
print("difference of two numbers: ", a-b)
print("multiplication of two numbers: ", a*b)
print("division of two numbers: ", a/b)
print("modulo division of two numbers: ", a%b)
print("floor division of two numbers: ", a//b)
print("exponentiation of two numbers: ", a**b)
